POSITIVE_WORDS = {
    "growth", "stronggrowth", "acceleratedgrowth", "expansion", "marketexpansion",
    "profit", "profits", "recordprofit", "profitsurge", "profitgrowth",
    "revenue", "revenuegrowth", "revenueincrease", "risingrevenue", "top-linegrowth",
    "earnings", "earningsgrowth", "earningsbeat", "earningssurprise", "strongearnings",
    "positiveoutlook", "bullishoutlook", "optimisticoutlook", "favorableoutlook",
    "guidanceupgrade", "raisedguidance", "upwardguidance", "forecastupgrade",
    "marketconfidence", "investorconfidence", "renewedconfidence", "strongconfidence",
    "bullishsentiment", "positivesentiment", "marketoptimism", "investoroptimism",
    "sharepricerally", "stockrally", "pricesurge", "sharesurge", "stocksurge",
    "shareappreciation", "capitalappreciation", "valuecreation",
    "dividend", "dividendincrease", "dividendgrowth", "specialdividend",
    "sharebuyback", "buybackprogram", "stockrepurchase",
    "strongfundamentals", "solidfundamentals", "improvingfundamentals",
    "financialstrength", "strongbalancesheet", "healthybalance sheet".replace(" ", ""),
    "lowdebt", "reduceddebt", "deleveraging",
    "cashflow", "strongcashflow", "positivecashflow", "freecashflowgrowth",
    "liquidity", "strongliquidity", "ampleliquidity",
    "marketleadership", "industryleader", "sectorleader",
    "competitiveadvantage", "moat", "strategicadvantage",
    "innovation", "productinnovation", "technologyleadership",
    "successfullaunch", "productlaunchsuccess", "newproductsuccess",
    "marketsharegain", "gainingmarketshare", "expandedmarketshare",
    "customergrowth", "usergrowth", "subscribergrowth",
    "strongdemand", "risingdemand", "robustdemand",
    "ordergrowth", "strongorderbook", "recordorders",
    "backloggrowth", "healthybacklog",
    "pricingpower", "marginexpansion", "improvingmargins",
    "costefficiency", "operationalefficiency", "productivitygains",
    "costoptimization", "leanoperations",
    "scalability", "scalablebusinessmodel",
    "strategicpartnership", "keypartnership", "newalliance",
    "jointventuresuccess", "strategicalliance",
    "acquisition", "value-accretiveacquisition", "successfulacquisition",
    "mergersynergies", "synergyrealization",
    "globalexpansion", "internationalgrowth", "newmarkets",
    "regulatoryapproval", "approvalreceived", "licensegranted",
    "favorableregulation", "regulatorytailwinds",
    "contractwin", "majorcontract", "long-termcontract",
    "renewedcontract", "contractextension",
    "strongpipeline", "robustpipeline",
    "executionexcellence", "strongexecution", "on-trackexecution",
    "milestoneachieved", "keymilestonereached",
    "positivecashposition", "netcashposition",
    "creditupgrade", "ratingupgrade",
    "analystupgrade", "buyrating", "outperformrating",
    "targetpriceincrease", "pricetargetraised",
    "institutionalbuying", "fundinflows",
    "insiderbuying", "managementconfidence",
    "long-termgrowth", "sustainablegrowth",
    "resilientbusiness", "defensivestrength",
    "brandstrength", "strongbrand",
    "customerloyalty", "highretention",
    "lowchurn", "reducedchurn",
    "improvingKPIs", "strongmetrics",
    "positivemomentum", "upwardmomentum",
    "markettailwinds", "favorableconditions",
    "economicrecovery", "sectorrecovery",
    "capacityexpansion", "increasedcapacity",
    "capexinvestment", "strategicinvestment",
    "digitaltransformationsuccess",
    "AIadoptionsuccess",
    "efficiencygains",
    "operatingleverage",
    "strongROE", "strongROI", "highreturns",
    "valueaccretivestrategy",
    "stronggovernance",
    "ESGleadership",
    "sustainabilityleadership",
    "greeninitiativessuccess",
    "carbonreductionachievements",
    "long-termvisibility",
    "predictableearnings",
    "earningsstability",
    "riskmitigationsuccess",
    "diversificationbenefits",
    "balancedportfolio",
    "strongdemandoutlook",
    "positivetradingupdate",
    "strongquarterlyresults",
    "strongannualresults",
    "beatexpectations",
    "aboveexpectations",
    "guidancereaffirmed",
    "confidencereaffirmed",
    "shareholdervaluecreation",
    "wealthcreation",
    "capitalefficiency",
    "returnofcapital",
    "strongpipelinevisibility",
    "positivemacroexposure",
    "growthtailwinds",
    "strongsectorpositioning",
    "pricingdiscipline",
    "marginresilience",
    "costcontrolsuccess",
    "operationalresilience",
    "robustbusinessmodel",
    "executiontrackrecord",
    "strategicclarity",
    "focusedstrategy",
    "managementcredibility",
    "experiencedleadership",
    "visionaryleadership",
    "long-termstrategy",
    "growthstrategyexecution",
    "earningsacceleration",
    "strongsalesgrowth",
    "pipelineconversionsuccess",
    "positivefreecashflow",
    "workingcapitalimprovement",
    "capitalstructureimprovement",
    "strongordervisibility",
    "positiveearningscall",
    "marketre-rating".replace("-", ""),
    "valuationuplift",
    "growth", "profit", "rise", "strong", "increase", "gain", "boost", "increased",
    "confidence", "more", "expansion", "better", "gold", "powerful", "stronger",
    "hires", "deals", "increasedprofit", "morebacking", "moresales", "upturn",
    "strategy", "investorconfidence", "forecastedgrowth", "positive", "trust",
    "moreinvestors", "increasedrevenue", "competitive", "larger",
    "advantage", "advantageous"
}

NEGATIVE_WORDS = {
    "decline", "decliningperformance", "marketdecline", "sharepricedrop",
    "stockпаде", "sell-off", "marketsell-off", "sharpsell-off",
    "loss", "losses", "netloss", "wideninglosses",
    "revenuedecline", "fallingrevenue", "top-linepressure",
    "earningsmiss", "missedexpectations", "belowexpectations",
    "profitwarning", "earningswarning",
    "negativeoutlook", "bearishoutlook", "pessimisticoutlook",
    "guidancedowngrade", "loweredguidance", "forecastcut",
    "lossofconfidence", "investorconcern", "marketconcern",
    "negativesentiment", "bearishsentiment", "marketpessimism",
    "volatility", "highvolatility", "marketturbulence",
    "uncertainty", "economicuncertainty", "policyuncertainty",
    "headwinds", "strongheadwinds", "macroheadwinds",
    "weakdemand", "softdemand", "demandslowdown",
    "orderdecline", "shrinkingorderbook",
    "marketshareloss", "losingmarketshare",
    "customerchurn", "highchurn", "userdecline",
    "subscriberlost".replace("lost", "loss"),
    "customerattrition",
    "pricingpressure", "margincompression", "shrinkingmargins",
    "costinflation", "risingcosts",
    "operationalefficiency".replace("efficiency", "inefficiency"),
    "executionissues",
    "missedtargets", "missedmilestones",
    "cashburn", "negativecashflow", "liquiditystress",
    "cashshortage", "fundingconcerns",
    "debtburden", "highleverage", "overleveraged",
    "creditdowngrade", "ratingdowngrade",
    "analystdowngrade", "sellrating", "underperformrating",
    "pricetargetcut", "valuationcut",
    "institutionalselling", "fundoutflows",
    "insiderselling",
    "managementuncertainty", "leadershipinstability",
    "executiveresignation", "CEOdeparture",
    "governanceissues", "corporategovernanceconcerns",
    "accountingissues", "financialirregularities",
    "restatement", "earningsrestatement",
    "regulatoryrisk", "regulatorypressure",
    "fines", "penalties", "legalrisk",
    "lawsuit", "litigationrisk",
    "investigation", "regulatoryinvestigation",
    "compliancefailure",
    "contractloss", "majorcontractloss",
    "failedacquisition", "integrationissues",
    "synergyshortfall",
    "strategicmissteps", "poorstrategy",
    "lackofdirection", "unclearstrategy",
    "competitivepressure", "intensecompetition",
    "disruptionrisk", "technologicaldisruption",
    "obsoleteproducts", "productfailure",
    "recall", "productrecall",
    "delayedlaunch", "failedlaunch",
    "weakpipeline", "pipelinedelays",
    "projectdelays", "costoverruns",
    "capexoverruns",
    "overexpansion", "capacityunderutilization",
    "marketsaturation",
    "economicslowdown", "recessionfears",
    "sectordownturn", "industrydecline",
    "cyclicalweakness",
    "foreignexchangelosses",
    "currencyheadwinds",
    "inflationpressure",
    "interestraterisk",
    "macroeconomicpressure",
    "reducedguidance",
    "withdrawnguidance",
    "visibilityconcerns",
    "earningsvolatility",
    "unpredictableearnings",
    "poorcashconversion",
    "workingcapitalstrain",
    "balancesheetweakness",
    "assetimpairment",
    "write-down".replace("-", ""),
    "write-off".replace("-", ""),
    "inventorybuild-up".replace("-", ""),
    "supplychaindisruption",
    "logisticsissues",
    "laborshortages",
    "strikeaction",
    "industrialaction",
    "operationaldisruption",
    "systemoutage",
    "cybersecuritybreach",
    "databreach",
    "reputationdamage",
    "branderosion",
    "negativepress",
    "mediascrutiny",
    "investorbacklash",
    "shareholderactivism",
    "proxybattle",
    "dividendcut",
    "dividendsuspension",
    "buybacksuspension",
    "capitalraise",
    "dilutionrisk",
    "equitydilution",
    "rightsissue",
    "emergencyfunding",
    "distressedfinancing",
    "bankcovenantbreach",
    "defaultrisk",
    "solvencyconcerns",
    "goingconcernwarning",
    "bankruptcyrisk",
    "restructuring",
    "downsizing",
    "layoffs",
    "cost-cuttingpressure".replace("-", ""),
    "storeclosures",
    "plantclosures",
    "assetsales",
    "firesale",
    "strategicretreat",
    "exitfrommarket",
    "reducedfootprint",
    "lossofkeycustomers",
    "supplierrisk",
    "concentrationrisk",
    "dependencyrisk",
    "poorROE",
    "lowreturns",
    "valuedestruction",
    "negativeROIC",
    "capitalinefficiency",
    "poorcapitalallocation",
    "missedgrowthopportunities",
    "stagnation",
    "flatgrowth",
    "zerogrowth",
    "earningsstagnation",
    "salesstagnation",
    "marketre-ratingdown".replace("-", ""),
    "valuationcompression",
    "bearmarketexposure",
    "negativetradingupdate",
    "weakquarterlyresults",
    "weakannualresults",
    "confidenceshaken",
    "investorskepticism",
    "credibilityloss",
    "trusterosion",
    "strategicuncertainty",
    "executionfailure",
    "operationalrisk",
    "fragilebusinessmodel",
    "structuraldecline",
    "long-termdecline".replace("-", ""),
    "terminalrisk",
    "fall", "weak", "drop", "decrease", "challenges", "problem",
    "closure", "tariff", "weaker", "downsize", "layoff", "bankruptcy",
    "troubles", "issues", "worries", "lackofconfidence",
    "hurt", "damage", "legalissue", "failure", "breakdown",
    "lessbacking", "detriment", "pressure", "under",
    "lesssales", "uncertain", "notrust"
}

def score_headlines(headlines: list[str]) -> int:
    score = 0

    for headline in headlines:
        text = headline.lower().replace(" ", "")

        score += sum(term in text for term in POSITIVE_WORDS)
        score -= sum(term in text for term in NEGATIVE_WORDS)

    return score
